// <auto-generated />
using System;
using DriveEasyLog.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveEasyLog.Persistence.Migrations
{
    [DbContext(typeof(DriveEasyContext))]
    [Migration("20260219035336_InitialIdentityAndVango")]
    partial class InitialIdentityAndVango
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DriveEasyLog.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AppVinculado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoAcesso")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoBusca")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<float>("LatBusca")
                        .HasColumnType("REAL");

                    b.Property<float>("LngBusca")
                        .HasColumnType("REAL");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Periodo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorMensal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Escola", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Lat")
                        .HasColumnType("REAL");

                    b.Property<float>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("LatAtual")
                        .HasColumnType("REAL");

                    b.Property<float>("LngAtual")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaAtualizacaoGps")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.PresencaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Confirmado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConfirmadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Embarcou")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HorarioEmbarque")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("VaiHoje")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Presencas");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Periodo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Aluno", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.Escola", "Escola")
                        .WithMany("Alunos")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveEasyLog.Domain.Motorista", "Motorista")
                        .WithMany("Alunos")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveEasyLog.Domain.Responsavel", "Responsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escola");

                    b.Navigation("Motorista");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Contrato", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.Aluno", "Aluno")
                        .WithOne("Contrato")
                        .HasForeignKey("DriveEasyLog.Domain.Contrato", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Motorista", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Pagamento", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.Contrato", "Contrato")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.PresencaDiaria", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.Aluno", "Aluno")
                        .WithMany("Presencas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveEasyLog.Domain.Viagem", "Viagem")
                        .WithMany("Presencas")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Veiculo", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.Motorista", "Motorista")
                        .WithOne("Veiculo")
                        .HasForeignKey("DriveEasyLog.Domain.Veiculo", "MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Viagem", b =>
                {
                    b.HasOne("DriveEasyLog.Domain.Motorista", "Motorista")
                        .WithMany("Viagens")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Aluno", b =>
                {
                    b.Navigation("Contrato");

                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Contrato", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Escola", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Motorista", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Veiculo");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Responsavel", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("DriveEasyLog.Domain.Viagem", b =>
                {
                    b.Navigation("Presencas");
                });
#pragma warning restore 612, 618
        }
    }
}
